### ISSUE TITLE
Console spammed with errors

### ISSUE THREAD

**Issue by Apeiros-46B** [LOOHP/InteractiveChat-DiscordSRV-Addon#14]
### Issue:

ICD is disabled on startup and DiscordSRV spams the console with errors
Issue is not present when ICD is removed from the server

**Server log:**
https://mclo.gs/LIn9srh

### Other Info:

**Plugin versions:**
DiscordSRV: 1.24.0
IC: 4.1.1.1
ICD: 4.1.1.7

**Server version:**
PurpurMC-1498 1.18.1

**Plugin list:**
![image](https://user-images.githubusercontent.com/61390942/149429471-67a7786f-585b-4b06-89cd-25fcf2c0dcaf.png)

**Comment by LOOHP** [comment]
```
[16:16:23] [Server thread/ERROR]: Error occurred while enabling InteractiveChatDiscordSrvAddon v4.1.1.7 (Is it up to date?)
github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 50001: Missing Access
```
Please read the Q&A section regarding this error [here](https://www.spigotmc.org/resources/interactivechat-discordsrv-addon-show-items-and-invs-on-discord-preview-discord-images-in-game.83917/)

**Comment by Apeiros-46B** [comment]
Ah, thanks
