### ISSUE TITLE
Instant fail on command 

### ISSUE THREAD

**Issue by mastermc05** [LOOHP/InteractiveChat-DiscordSRV-Addon#16]
Any command with which i can see other's inventories instantly fail, i have all exiting perms on server (the *) and i am the owner of bot and me and the bot have the administrator permission 

others commands works well

**Comment by mastermc05** [comment]
also no error in console

**Comment by mastermc05** [comment]
version 4.1.3.7 (both)
![Screenshot_20220315-153045_Discord](https://user-images.githubusercontent.com/63639746/158388487-819aa183-30d5-4fc0-8866-3e7f80654e30.png)
/inv works in like 3-5 seconds, while it says that it's thinking
/invauser shows error instantly, feels like not even some ms of delay

**Comment by LOOHP** [comment]
Can you show me your InteractiveChatDiscordSrvAddon config?

**Comment by mastermc05** [comment]
ugh, yeah, missed the permission config 
can you add an informative ephemeral error message that the player don't have permission?

**Comment by mastermc05** [comment]
now works fine btw, thanks

**Comment by LOOHP** [comment]
> can you add an informative ephemeral error message that the player don't have permission?

It is currently a bug in the mobile version of discord, it still allows you to run the command despite lacking permission. You'll see what I mean by that if you try to run the command when you don't have permission on PC.

**Comment by mastermc05** [comment]
oh, then ok, thanks anyway
