### ISSUE TITLE
Adventure Minimessage support

### ISSUE THREAD

**Issue by RiceCX** [LOOHP/InteractiveChat-DiscordSRV-Addon#17]
Are you able to add in mini message support? At the moment, /playerlist is generated like this. 

![image](https://user-images.githubusercontent.com/26664578/165000899-cc6118cc-1d4d-4f45-8054-33dbe8e501fe.png)

If you need to convert those into Kyori components, you can call `Minimessage#minimessage#deserialize(<string>)` which returns a component object.

**Comment by LOOHP** [comment]
`<gold><bold>Owner <reset><gray>` is your prefix from your permission plugin?

**Comment by RiceCX** [comment]
Yes it is

**Comment by LOOHP** [comment]
Added in 4.1.4.14
