### ISSUE TITLE
1.19 disconnect

### ISSUE THREAD

**Issue by disqetow** [LOOHP/InteractiveChat-DiscordSRV-Addon#19]
Player paste image at discord channel
and preview it in game will disconnect

console spam: https://pastebin.com/0gPtkndC

**Comment by LOOHP** [comment]
Which version of ProtocolLib are you using?

**Comment by disqetow** [comment]
b568 form jenkins

**Comment by LOOHP** [comment]
I'm unable to reproduce this problem. Try updating both ProtocolLib and InteractiveChat-DiscordSRV-Addon to the latest dev build on a **Paper** test server.

**Comment by disqetow** [comment]
try link like this: https://media.discordapp.net/attachments/686764243856654370/883742450248716330/tenor.gif

**Comment by LOOHP** [comment]
I can't seem to open this link.

![image](https://user-images.githubusercontent.com/22975196/174421941-7ee44b81-d272-4325-a1d5-9e6954939af2.png)

**Comment by disqetow** [comment]
someone just post it to discord channel, and preview it in game, and disconnect

**Comment by LOOHP** [comment]
Give Build #191 on [my build server](https://ci.loohpjames.com) a try

**Comment by disqetow** [comment]
It fixed now, thank !
