### ISSUE TITLE
[BUG] Random UUIDs after text in DiscordSRV

### ISSUE THREAD

**Issue by RobotHanzo** [LOOHP/InteractiveChat-DiscordSRV-Addon#2]
![Attachment](https://cdn.robothanzo.dev/DiscordCanary_h8ZAKKSuW4.png)
![Attachment](https://cdn.robothanzo.dev/javaw_rgSOWDO0GI.png)
The image explains the bug
Installed plugins: ![Plugins](https://cdn.robothanzo.dev/javaw_W1HlQGgUpH.png)

**Comment by RobotHanzo** [comment]
https://github.com/LOOHP/InteractiveChat/commit/e5a7c7c3f4b96fbdd9f70d14a89e84563f728254
After using the build from that commit it turned into
![Attachment](https://cdn.robothanzo.dev/DiscordCanary_PDhbQ1iE2e.png)

**Comment by LOOHP** [comment]
Try updating to InteractiveChat-3.2.10.6

**Comment by RobotHanzo** [comment]
Works now, thanks!
Though console still includes the UUID

**Comment by LOOHP** [comment]
Yea, I'll see if I can do anything about that in the future, closing this for now.

**Comment by RobotHanzo** [comment]
Good luck fixing it 👍
