### ISSUE TITLE
[Feature Request] Death message language

### ISSUE THREAD

**Issue by Pantera07** [LOOHP/InteractiveChat-DiscordSRV-Addon#26]
DiscordSRV native death messages are only available in English.
Add a configuration to display the death message in the language set in `Resources.Language`.

**Comment by LOOHP** [comment]
ICD's death messages overriding DiscordSRV's are already localized

**Comment by Pantera07** [comment]
> 

![화면 캡처 2022-09-20 201846](https://user-images.githubusercontent.com/89838384/191244554-7ae412eb-9c41-4dd0-9093-cfdfe363eef2.png)

I want localization of all death messages.

**Comment by Pantera07** [comment]
https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/commit/e5a88d140dcdf4c82645003af37f0877159f2b0d
Fast Support! Thanks!

**Comment by LOOHP** [comment]
No problem :)

**Comment by Anath4n** [comment]
Excuse me, I'm learning about this, what does ICD mean?

**Comment by LOOHP** [comment]
ICD is an abbreviation for **I**nteractive**C**hat**D**iscordSRVAddon
And you can just put that language code into the `Language` option in the ICD config

**Comment by Anath4n** [comment]
> ICD is an abbreviation for **I**nteractive**C**hat**D**iscordSRVAddon And you can just put that language code into the `Language` option in the ICD config


Thanks for the help, fast and effective support!
