### ISSUE TITLE
Head item size is displayed smaller than actual size.

### ISSUE THREAD

**Issue by Pantera07** [LOOHP/InteractiveChat-DiscordSRV-Addon#28]
![2022-12-20_00 07 24](https://user-images.githubusercontent.com/89838384/208456508-fd0495ed-be03-46c6-911f-6b58f985db62.png)
![Inventory_0](https://user-images.githubusercontent.com/89838384/208456167-0dd0022e-2ce9-4c63-8980-b260d1896e6e.png)
-----
![2022-12-19_23 55 46](https://user-images.githubusercontent.com/89838384/208455213-ffae4886-7678-476c-9086-5f740fd03bc5.png)
![Inventory_0](https://user-images.githubusercontent.com/89838384/208455406-b7a40e9b-5602-42b0-8020-684b1cefe86c.png)
-----
![2022-12-19_23 55 40](https://user-images.githubusercontent.com/89838384/208455528-b063af87-d121-42e2-92b6-a3263e925a3b.png)
![Inventory_0 (1)](https://user-images.githubusercontent.com/89838384/208455570-17697b89-5bff-49da-9b05-434f8ac8468f.png)
-----
![2022-12-19_23 55 36](https://user-images.githubusercontent.com/89838384/208455832-47de7d82-502c-4755-b0be-da6565dc46d1.png)
![Inventory_0 (2)](https://user-images.githubusercontent.com/89838384/208455605-11795d91-49e9-4467-acd0-38b425103440.png)
-----
![2022-12-19_23 55 28](https://user-images.githubusercontent.com/89838384/208455631-37bea7d5-f14c-45a6-a08b-bf6b60d98d76.png)
![Inventory_0 (3)](https://user-images.githubusercontent.com/89838384/208455647-679e48d4-049d-48fc-92de-7d918d1d16df.png)

**Comment by LOOHP** [comment]
Fixed in the assets.
