### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by MeekOnGithub** [LOOHP/InteractiveChat-DiscordSRV-Addon#30]
(title self-explanatory) 

Don't you have a discord server, that would be more easy for support

Thanks ! 

It look like this without placeholders :
![image](https://user-images.githubusercontent.com/89902968/220541039-3660c1bd-c382-44cb-bd96-06c38a89233b.png)

**Comment by LOOHP** [comment]
There is!
https://loohpjames.com/dev-discord

**Comment by MeekOnGithub** [comment]
Cant' join, i reached the max of servers that i can join and when i leave its still tell me this, can you help on github please ?

**Comment by LOOHP** [comment]
You have to download the placeholderapi expansions.

**Comment by MeekOnGithub** [comment]
Ok, lemm try

**Comment by MeekOnGithub** [comment]
Working, thanks you so much !
