### ISSUE TITLE
Showing `%player_name%'s inventory` instead of the real player name in chat

### ISSUE THREAD

**Issue by ItzMiracleOwO** [LOOHP/InteractiveChat-DiscordSRV-Addon#32]
### Expected behavior

Show player name in chat

### Actual behavior

![image](https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/assets/76854136/e5d3c0c0-dbeb-43f3-a3f1-07c5aea4df15)

### Steps to reproduce

Use `[inv]` in chat

### Server software and version

This server is running Paper version git-Paper-47 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: aea9cdd)

**Comment by LOOHP** [comment]
You need to download the placeholderapi player expansion.

**Comment by ItzMiracleOwO** [comment]
![image](https://github.com/LOOHP/InteractiveChat-DiscordSRV-Addon/assets/76854136/f3285e71-1c74-4bca-a54d-47111f0fd2f8)
placeholderapi is already downloaded

**Comment by ItzMiracleOwO** [comment]
@LOOHP

**Comment by LOOHP** [comment]
You are missing the player expansion of papi, not papi itself.

**Comment by ItzMiracleOwO** [comment]
Where can I download that, Do I put that in the plugins too?

**Comment by ItzMiracleOwO** [comment]
@LOOHP
