### ISSUE TITLE
Exclude video from being processed

### ISSUE THREAD

**Issue by cupang-afk** [LOOHP/InteractiveChat-DiscordSRV-Addon#35]
as the title said because when sending a video you will get this error

```java
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getHeight()" because "image" is null
```

the plugin already sent the video as a link in the minecraft chat but still trying to proceed the video as an image

**Comment by LOOHP** [comment]
Should probably not happen anymore as it only processes media if it is not a video.
