### ISSUE TITLE
Multiple triggers to call Playerlist !

### ISSUE THREAD

**Issue by MeowIce** [LOOHP/InteractiveChat-DiscordSRV-Addon#36]
Multiple triggers to call up the Playerlist (tab list) are amazing. It does not limit users to only pre-configured word-wrap. For example, we can both have "playerlist" and "listplayers" working, so the config should look like this:
`DiscordChatChannelListCommandMessage: ["playerlist", "listplayers"]`
And both of them should show the tab list as expected.

**Comment by LOOHP** [comment]
I think you've probably opened this suggestion in the wrong place. `DiscordChatChannelListCommandMessage` is in the DiscordSRV config, not ICD's.
