### ISSUE TITLE
IncompatibleClassChangeError - AccountLinkManager

### ISSUE THREAD

**Issue by Pryzinho** [LOOHP/InteractiveChat-DiscordSRV-Addon#42]
Error: https://gist.github.com/Pryzinho/fba0bc1f3869744b077c53b7051f5297
Step to reproduce: Just download DiscordSrv, InteractiveChat, InteractiveChat-DiscordSRV-Addon.

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
DiscordSRV v1.27.1-SNAPSHOT
 You are running InteractiveChat version: 4.2.9.0

**Comment by LOOHP** [comment]
You need to update ICD dev build and DiscordSRV.
