### ISSUE TITLE
"You cannot do that in this channel"

### ISSUE THREAD

**Issue by TomLewis** [LOOHP/InteractiveChat-DiscordSRV-Addon#48]
Every time I try and use one of the slash commands I get the error `You cannot do that in this channel!`
Is this a permission thing? how do I fix it?

**Comment by LOOHP** [comment]
Slash commands are only allowed on channels listed in the discordsrv config.

**Comment by TomLewis** [comment]
Thats a great idea, I like that, what is the placeholder called? I tried CTRL+F for commands/channel and cant see it! I swear my brain isnt working

**Comment by LOOHP** [comment]
I think it is at the top of the discordsrv config. The place where you choose which channel in discord to link to which chat channel in game.

**Comment by TomLewis** [comment]
omg im looking in your config not discordSRVS! Thats where im getting lost!

**Comment by TomLewis** [comment]
In this part?
```
# Channel links from game to Discord
# syntax is Channels: {"in-game channel name from Minecraft": "numerical channel ID from Discord", "another in-game channel name from Minecraft": "another numerical channel ID from Discord"}
#
# All of DiscordSRV's messages will go to the first channel unless there's a channel for that type of messages defined:
# when using a compatible chat plugin, the channel name will be the one from that plugin (for chat messages)
#  - If you're using TownyChat, the default channel is usually called "general" instead of "global"
# for player chat messages (when not using a chat plugin): global
# for server start/stop messages: status
# for achievement/advancement messages: awards
# for death messages: deaths
# for join messages: join
# for leave messages: leave
# for dynmap messages: dynmap
# for watchdog messages: watchdog
# for /discord broadcast: broadcasts (unless specified in the command)
# for account linking: link
#
# The first part of channel pairs is not the Discord channel name!
# Run "/discord reload" after changing this option to apply
Channels: {"global": "209996994146467842", "link": "1204541288909766756", "punishments": "958458206529663046"}
```

So I have to set it in this section? What do I set as the channels type? I cant see one thats speicifc to Slash commands?

https://docs.discordsrv.com/config

**Comment by LOOHP** [comment]
Just like them to Minecraft channels names that don't exist.

**Comment by TomLewis** [comment]
ok that worked.

First impressions, this plugin is INSANE. And even works with offline players!

Litearlly no idea how you have managed to build this, its incredible.

**Comment by LOOHP** [comment]
Glad you liked the plugin!
