### ISSUE TITLE
many warns + errors on server start/stop

### ISSUE THREAD

**Issue by homerek111** [LOOHP/InteractiveChat-DiscordSRV-Addon#59]
this is spamming my console - plugin works fine
https://pastebin.com/xGj0pZZ5

another one from another server: 
https://pastebin.com/Dm0YCnrf

and this error of library on server launch: 
https://pastebin.com/DA5LDgNF

and this one while shutting down: 
https://pastebin.com/AxAnpmMC

**Comment by LOOHP** [comment]
My API service was down yesterday and should be resolved now.
