### ISSUE TITLE
EssentialsXDiscord support

### ISSUE THREAD

**Issue by xamionex** [LOOHP/InteractiveChat-DiscordSRV-Addon#7]
Would be pretty cool if you did this, EssentialsXDiscord kinda does separate messages unlike DiscordSRV so i don't know how it'll work. And by the way, thank you for making this plugin

**Comment by LOOHP** [comment]
I've looked into EssentialsXDiscord lately and it seems to be impossible to do what InteractiveChatDiscordSRVAddon adds to DiscordSRV over there. The reason being that, unlikely DiscordSRV, EssentialsXDiscord does not have sufficient information contained in the events that they fire when a discord message is posted. For example, it isn't possible to get the underlying advancement for an advancement message sent to discord. 

I will reconsider adding support when better api is introduced. Or you can urge them to do that if you really want to.
